name = "fileshare"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "LINK", id = "057b6c3d21694476b1c745d3bc930405",preview_id='111'}
]
[site]
bucket = "./static/dist"
